### ISSUE TITLE
Checklist of actionable feedback from second beta pilot

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#107]
Summarized from [second beta pilot notes](https://docs.google.com/document/d/1uD77baBIGY7SiqeuhyKDw95I-fqJKFLorEw3qYW_gKs/edit#)

Typos / errors: (all addressed in https://github.com/datacarpentry/astronomy-python/pull/108)

- [x] Remove notebook directory 
- [x] the documentation link for the column names under the Pan-STARRS table is incorrect - it just links back to the JOIN episode - should link to: https://gea.esac.esa.int/archive/documentation/GDR2/Gaia_archive/chap_datamodel/sec_dm_external_catalogues/ssec_dm_panstarrs1_original_valid.html
- [x] TYPO: Episode 8  "At the very least, those details (and the isochrone line) could be called out in the legend" (legend should be caption)
- [x] TYPO: In plotting GD-1 with annotations exercise, "plot_cmd_function"  should be "plot_cmd_selection"

Set-up and Instructor notes: 

- [x] include paper link in setup as recommended reading before workshop - https://github.com/datacarpentry/astronomy-python/pull/108
- [x] Note in Instructor notes that "Checking the match" section can be skipped - https://github.com/datacarpentry/astronomy-python/pull/108
- [ ] ~~Make the setup instructions more prominent on the workshop website.~~ --> OUT OF SCOPE - requires edit to https://github.com/carpentries/workshop-template

Callouts and explanations to add:

- [x] Add callout for asynchronous queries section about getting different values that instructor in the table when using Top Ten.  ​'Top Ten' just grabs 10 results but that the system isn't organized in a specific way unless you code in something to ask for it to organize by. The fact the source_ids are all random and not sequential backs up that idea for me too - https://github.com/datacarpentry/astronomy-python/pull/108
- [x] ~~Add callout in working with units section - For arcmin: Make sure you use the single-quote ' on you keyboard that is beside the "Enter" key! The character up on the left hand side of the number row is a tick  that looks similar, but doesn't work the same.~~
     - I don't see anywhere where learners have to use the single-quote to represent arcmin. The solutions have them use u.arcmin. @abostroem - is this callout neccessary? 
- [x] Style sheets, add callout about how to swap back to the default style. Answer `plt.style.use('default')` - https://github.com/datacarpentry/astronomy-python/pull/108
- [x] #119
- [x] Make sure GD-1 is introduced in lesson: "GD-1 is a stellar stream around the Milky Way. This means it is a collection of stars that we believe was once part of a bound clump, but the gravitational influence of the Milky Way has torn it apparent and spread it over an arc that traces out its orbit on the sky.
This is interesting, because if the original bound clump was a dwarf galaxy, understanding its orbit with sufficient precision allows us to measure the mass of the Milky Way, which is very important for understanding the future and pass of the Milky Way as a whole.  But that is much easier to do if we have a coordinate system aligned with the stream because that makes fitting the location of the stars much easier mathematically - it's a line instead of some weird funky curve.
Additionally, this stream is especially interesting because it has "gaps", which have a natural interpretation as being caused by the influence of small clumps of dark matter passing near the stream.  And knowing the typical rate of these gaps tells you about the typical size and density of these clumps, which turns out to be one of the best probes we have of the fine structure of dark matter."
- [x] Add explanation for “which points are in the polygon” exercise: This exercise could use a little more context (e.g. we never actually say that contains_points is a method on the Polygon object). Perhaps “The results is a Polygon object which has a contains_points method built in. This allows us to pass contains_points a list of points and for each point this will tell us if the points are contained within the polygon. Then in the exercise: Your points list should be a list of tuples, where each tuple two elements representing an x,y pair. Call contains_points on the polygon we just created (e.g. polygon.contains_points), passing it the list of points you just created 
- [ ] Write the data - This section intro could use a sentence calling out reproducibility
- [x] plotting GD-1 with annotations exercise - specify creating one of the arrows on the plot (e.g. spur, gap)

Other:
- [x] British vs American spelling of neighbor in queries (and possibly other things)
- [x] Rename data directory to something explicit like back up data?
- [x] Do we ever re use the front_to_back function? Could this just be code?
- [x] At the end of episode 7, could we use plot_cmd to plot the winner_df  points too? Maybe the only modification would be to not set the color in the function itself?
- [x] Add link to onboarding Youtube video - https://github.com/datacarpentry/astronomy-python/pull/108

**Comment by rudyphd** [comment]
Hi Erin, I added the task starting "Make sure GD-1 is introduced in lesson" to the index.md page.

**Comment by abostroem** [comment]
I agree, arcmin comment looks like its about typing notes and not actually in the lesson

**Comment by abostroem** [comment]
@philrosenfield The Gaia catalog has photometry in it (G, BP, and RP I think) but to make our isochrone cut, we go to the PanSTARRS catalog and look at g-i. Can you give me a few sentences on why the Gaia photometry isn't sufficient for the isochrone CMD cut?

**Comment by philrosenfield** [comment]
Gaia filters are too wide to be useful for this type of analysis. (I can go into more detail after the weekend if needed.)
________________________________

**Comment by abostroem** [comment]
A few more details next week would be great - for the person who says "why is wide a bad thing..."
